/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsComponentsProductionChartRouteImport } from './routes/docs/components/production-chart'
import { Route as DocsComponentsOgMapRouteImport } from './routes/docs/components/og-map'
import { Route as DocsComponentsAssetDetailCardRouteImport } from './routes/docs/components/asset-detail-card'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsProductionChartRoute =
  DocsComponentsProductionChartRouteImport.update({
    id: '/docs/components/production-chart',
    path: '/docs/components/production-chart',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsOgMapRoute = DocsComponentsOgMapRouteImport.update({
  id: '/docs/components/og-map',
  path: '/docs/components/og-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAssetDetailCardRoute =
  DocsComponentsAssetDetailCardRouteImport.update({
    id: '/docs/components/asset-detail-card',
    path: '/docs/components/asset-detail-card',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/components/asset-detail-card': typeof DocsComponentsAssetDetailCardRoute
  '/docs/components/og-map': typeof DocsComponentsOgMapRoute
  '/docs/components/production-chart': typeof DocsComponentsProductionChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/components/asset-detail-card': typeof DocsComponentsAssetDetailCardRoute
  '/docs/components/og-map': typeof DocsComponentsOgMapRoute
  '/docs/components/production-chart': typeof DocsComponentsProductionChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/components/asset-detail-card': typeof DocsComponentsAssetDetailCardRoute
  '/docs/components/og-map': typeof DocsComponentsOgMapRoute
  '/docs/components/production-chart': typeof DocsComponentsProductionChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/docs/installation'
    | '/docs/components/asset-detail-card'
    | '/docs/components/og-map'
    | '/docs/components/production-chart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/docs/installation'
    | '/docs/components/asset-detail-card'
    | '/docs/components/og-map'
    | '/docs/components/production-chart'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/docs/installation'
    | '/docs/components/asset-detail-card'
    | '/docs/components/og-map'
    | '/docs/components/production-chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsComponentsAssetDetailCardRoute: typeof DocsComponentsAssetDetailCardRoute
  DocsComponentsOgMapRoute: typeof DocsComponentsOgMapRoute
  DocsComponentsProductionChartRoute: typeof DocsComponentsProductionChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/production-chart': {
      id: '/docs/components/production-chart'
      path: '/docs/components/production-chart'
      fullPath: '/docs/components/production-chart'
      preLoaderRoute: typeof DocsComponentsProductionChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/og-map': {
      id: '/docs/components/og-map'
      path: '/docs/components/og-map'
      fullPath: '/docs/components/og-map'
      preLoaderRoute: typeof DocsComponentsOgMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/asset-detail-card': {
      id: '/docs/components/asset-detail-card'
      path: '/docs/components/asset-detail-card'
      fullPath: '/docs/components/asset-detail-card'
      preLoaderRoute: typeof DocsComponentsAssetDetailCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsComponentsAssetDetailCardRoute: DocsComponentsAssetDetailCardRoute,
  DocsComponentsOgMapRoute: DocsComponentsOgMapRoute,
  DocsComponentsProductionChartRoute: DocsComponentsProductionChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
