// Components

export type {
  AlignedChartSeries,
  Annotation,
  AnnotationStats,
  AnnotationType,
  AnnotationTypeMeta,
  AssetCardSlot,
  AssetCardSlots,
  AssetDetailCardProps,
  AssetDetailSection,
  ChartAggregation,
  ChartAxis,
  ChartConfig,
  ChartControlSettings,
  ChartDerivationResampleConfig,
  ChartFontWeight,
  ChartGroupIssue,
  ChartGroupProps,
  ChartKind,
  ChartProps,
  ChartResampleConfig,
  ChartResolution,
  ChartSeriesConfig,
  ChartSeriesDerivationContext,
  ChartSeriesReference,
  ChartTypography,
  ChartValueAxis,
  ChartValueLocation,
  ChartYValueFormatContext,
  ChartYValueFormatter,
  ClusterMarkerProps,
  DateInput,
  DeclineCurveProps,
  DeclineMathBuffers,
  DerivedChartSeriesConfig,
  EquationType,
  EventTimelineProps,
  FilterChip,
  FilterChipsProps,
  ForecastConfig,
  HyperbolicParams,
  LayoutOptions,
  LineChartProps,
  LineChartSeriesMeta,
  MapControlId,
  MapControlsProps,
  MapLayerId,
  MapProps,
  MapTooltipProps,
  MiniCardItem,
  MiniCardProps,
  NormalizedEvent,
  OverlayManagerProps,
  PositionedEvent,
  PreparedChart,
  PreparedChartGroup,
  PreparedChartSeries,
  PreparedChartWindow,
  PreparedLineChart,
  PreparedRelatedChart,
  PrepareLineChartOptions,
  ProductionChartProps,
  RelatedChartColorMode,
  RelatedChartConfig,
  RelatedChartDerivationContext,
  RelatedChartKind,
  RelatedChartPointContext,
  ResolvedChartTypography,
  Segment,
  SegmentParams,
  SelectedOverlayFeature,
  SelectionPanelProps,
  SelectionSummaryCardProps,
  TimelineDomain,
  TimelineGroup,
  TimelineGroupMode,
  TimelineLegendEntry,
  TimelineTick,
  VarianceRelatedChartOptions,
  WellEventGroup,
  WellEventTypeMeta,
} from "./components";
export {
  ANNOTATION_TYPE_GROUPS,
  ANNOTATION_TYPE_META,
  AssetDetailCard,
  adjustQiFromDrag,
  assetToMiniCard,
  buildTimelineTicks,
  Chart,
  ChartGroup,
  calculateChartZoomRange,
  colorForAnnotation,
  colorForEvent,
  computeAnnotationStats,
  computeForecast,
  computeTimelineDomain,
  computeVariance,
  createBuffers,
  createVarianceRelatedChart,
  createXValueFormatter,
  DEFAULT_CHART_CONTROL_SETTINGS,
  DEFAULT_CHART_TYPOGRAPHY,
  DEFAULT_RIGHT_AXIS_SERIES,
  DEFAULT_SEGMENT_PARAMS,
  DEFAULT_SERIES_COLORS,
  DEFAULT_SERIES_LABELS,
  DeclineCurve,
  detectTimeScale,
  EVENT_TYPE_GROUPS,
  EVENT_TYPE_META,
  EventTimeline,
  endOfTimeBucket,
  evalAtTime,
  evalSegment,
  eventTypeMeta,
  FilterChips,
  formatAdaptiveTimeTick,
  formatChartYValue,
  formatEventDate,
  formatEventDuration,
  formatEventRange,
  formatTimelineTick,
  fractionForTime,
  generateDailyProduction,
  generateSampleProduction,
  getChartBucketRange,
  getChartYExtent,
  getTimeSeriesAssociatedType,
  getTimeSeriesType,
  groupEventsByPeriod,
  hasLanes,
  humanizeEventType,
  insertSegmentAt,
  LineChart,
  layoutTimeline,
  Map,
  MapControls,
  MIN_SEGMENT_WIDTH,
  MiniCard,
  nextAnnotationId,
  nextSegmentId,
  normalizeEvents,
  normalizeSegments,
  OverlayManager,
  overlayFeatureToMiniCard,
  ProductionChart,
  prepareChartGroup,
  prepareChartWindow,
  prepareLineChart,
  prepareRelatedChart,
  removeSegment,
  resampleChartSeries,
  resolveChartTypography,
  resolveGroupMode,
  resolveRelatedChartColor,
  SelectionPanel,
  SelectionSummaryCard,
  shouldShowTypeChip,
  startOfTimeBucket,
  timelineLanes,
  timelineLegend,
  toEpochMs,
  updateForecastAndVariance,
  withAlpha,
} from "./components";
// UI primitives
export { Tooltip, TooltipContent, TooltipProvider, TooltipRoot, TooltipTrigger } from "./components/ui/tooltip";
export type {
  ChartGroupContext,
  ChartGroupEvent,
  LineChartMachine,
  LineChartMachineContext,
  LineChartMachineEvent,
  LineChartMachineInput,
  MapContext,
  MapEvent,
  MapInput,
  MapMachine,
} from "./machines";
// Machines (XState)
export { chartGroupMachine, lineChartMachine, mapMachine } from "./machines";

// Schemas
export {
  AssetArraySchema,
  AssetSchema,
  AssetTypeConfigSchema,
  CoordinatesSchema,
  DataPointSchema,
  FieldConfigSchema,
  MapOverlaySchema,
  parseAssets,
  safeParseAssets,
  TimeSeriesSchema,
  WellEventArraySchema,
  WellEventAttachmentSchema,
  WellEventSchema,
} from "./schemas";
export type { SqlJsDatabase } from "./services";
// Services
export { createSqliteStore, InMemoryStore, LocalStorageStore, migrateStore, SqliteStore } from "./services";
// Core Types
// Well-specific types (O&G convenience)
export type {
  Asset,
  AssetCluster,
  AssetQuery,
  AssetStatus,
  AssetStore,
  AssetType,
  AssetTypeConfig,
  BuiltInAssetType,
  BuiltInWellEventType,
  ColorScheme,
  Coordinates,
  CurveType,
  DataPoint,
  FieldConfig,
  FluidType,
  Frequency,
  LineGeometry,
  MapOverlay,
  MapViewState,
  OverlayFeatureOverride,
  OverlayStyle,
  OverlayType,
  PolygonGeometry,
  SavedMapView,
  SeriesType,
  StoreExport,
  TimeSeries,
  Trajectory,
  Unit,
  WellEvent,
  WellEventAttachment,
  WellEventType,
  WellProperties,
  WellType,
} from "./types";
// Utilities
export {
  computeBounds,
  csvRowToAsset,
  filterByValidCoordinates,
  filterPlottable,
  fitBounds,
  formatNumber,
  getAssetColor,
  getTimeSeries,
  groupBy,
  isValidCoordinates,
} from "./utils";
