// Re-export from shared theme — map components import from here for backwards compatibility
export {
  ACCENT,
  ACCENT_10,
  ACCENT_15,
  ACCENT_30,
  ACCENT_60,
  ACTIVE_BG,
  BLUR_LG,
  BLUR_MD,
  BLUR_SM,
  BORDER,
  BORDER_INPUT,
  BORDER_SUBTLE,
  BUTTON_BG,
  DANGER,
  DANGER_BG,
  FONT_FAMILY,
  HOVER_BG,
  INPUT_BG,
  PANEL_BG,
  PANEL_BG_LIGHT,
  SHADOW_MD,
  SHADOW_SM,
  STATUS_COLORS,
  TEXT_FAINT,
  TEXT_HEADING,
  TEXT_MUTED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TYPE_COLORS,
  WELL_TYPE_COLORS,
} from "../../theme";
