/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesSchemasRouteImport } from './routes/utilities/schemas'
import { Route as UtilitiesHelpersRouteImport } from './routes/utilities/helpers'
import { Route as ComponentsSelectionPanelRouteImport } from './routes/components/selection-panel'
import { Route as ComponentsOverlayManagerRouteImport } from './routes/components/overlay-manager'
import { Route as ComponentsMapRouteImport } from './routes/components/map'
import { Route as ComponentsLineChartRouteImport } from './routes/components/line-chart'
import { Route as ComponentsForecastLineChartRouteImport } from './routes/components/forecast-line-chart'
import { Route as ComponentsAssetDetailCardRouteImport } from './routes/components/asset-detail-card'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesSchemasRoute = UtilitiesSchemasRouteImport.update({
  id: '/utilities/schemas',
  path: '/utilities/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesHelpersRoute = UtilitiesHelpersRouteImport.update({
  id: '/utilities/helpers',
  path: '/utilities/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectionPanelRoute =
  ComponentsSelectionPanelRouteImport.update({
    id: '/components/selection-panel',
    path: '/components/selection-panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsOverlayManagerRoute =
  ComponentsOverlayManagerRouteImport.update({
    id: '/components/overlay-manager',
    path: '/components/overlay-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsMapRoute = ComponentsMapRouteImport.update({
  id: '/components/map',
  path: '/components/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsLineChartRoute = ComponentsLineChartRouteImport.update({
  id: '/components/line-chart',
  path: '/components/line-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsForecastLineChartRoute =
  ComponentsForecastLineChartRouteImport.update({
    id: '/components/forecast-line-chart',
    path: '/components/forecast-line-chart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsAssetDetailCardRoute =
  ComponentsAssetDetailCardRouteImport.update({
    id: '/components/asset-detail-card',
    path: '/components/asset-detail-card',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/asset-detail-card': typeof ComponentsAssetDetailCardRoute
  '/components/forecast-line-chart': typeof ComponentsForecastLineChartRoute
  '/components/line-chart': typeof ComponentsLineChartRoute
  '/components/map': typeof ComponentsMapRoute
  '/components/overlay-manager': typeof ComponentsOverlayManagerRoute
  '/components/selection-panel': typeof ComponentsSelectionPanelRoute
  '/utilities/helpers': typeof UtilitiesHelpersRoute
  '/utilities/schemas': typeof UtilitiesSchemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/asset-detail-card': typeof ComponentsAssetDetailCardRoute
  '/components/forecast-line-chart': typeof ComponentsForecastLineChartRoute
  '/components/line-chart': typeof ComponentsLineChartRoute
  '/components/map': typeof ComponentsMapRoute
  '/components/overlay-manager': typeof ComponentsOverlayManagerRoute
  '/components/selection-panel': typeof ComponentsSelectionPanelRoute
  '/utilities/helpers': typeof UtilitiesHelpersRoute
  '/utilities/schemas': typeof UtilitiesSchemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/asset-detail-card': typeof ComponentsAssetDetailCardRoute
  '/components/forecast-line-chart': typeof ComponentsForecastLineChartRoute
  '/components/line-chart': typeof ComponentsLineChartRoute
  '/components/map': typeof ComponentsMapRoute
  '/components/overlay-manager': typeof ComponentsOverlayManagerRoute
  '/components/selection-panel': typeof ComponentsSelectionPanelRoute
  '/utilities/helpers': typeof UtilitiesHelpersRoute
  '/utilities/schemas': typeof UtilitiesSchemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/asset-detail-card'
    | '/components/forecast-line-chart'
    | '/components/line-chart'
    | '/components/map'
    | '/components/overlay-manager'
    | '/components/selection-panel'
    | '/utilities/helpers'
    | '/utilities/schemas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/asset-detail-card'
    | '/components/forecast-line-chart'
    | '/components/line-chart'
    | '/components/map'
    | '/components/overlay-manager'
    | '/components/selection-panel'
    | '/utilities/helpers'
    | '/utilities/schemas'
  id:
    | '__root__'
    | '/'
    | '/components/asset-detail-card'
    | '/components/forecast-line-chart'
    | '/components/line-chart'
    | '/components/map'
    | '/components/overlay-manager'
    | '/components/selection-panel'
    | '/utilities/helpers'
    | '/utilities/schemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsAssetDetailCardRoute: typeof ComponentsAssetDetailCardRoute
  ComponentsForecastLineChartRoute: typeof ComponentsForecastLineChartRoute
  ComponentsLineChartRoute: typeof ComponentsLineChartRoute
  ComponentsMapRoute: typeof ComponentsMapRoute
  ComponentsOverlayManagerRoute: typeof ComponentsOverlayManagerRoute
  ComponentsSelectionPanelRoute: typeof ComponentsSelectionPanelRoute
  UtilitiesHelpersRoute: typeof UtilitiesHelpersRoute
  UtilitiesSchemasRoute: typeof UtilitiesSchemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/schemas': {
      id: '/utilities/schemas'
      path: '/utilities/schemas'
      fullPath: '/utilities/schemas'
      preLoaderRoute: typeof UtilitiesSchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/helpers': {
      id: '/utilities/helpers'
      path: '/utilities/helpers'
      fullPath: '/utilities/helpers'
      preLoaderRoute: typeof UtilitiesHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/selection-panel': {
      id: '/components/selection-panel'
      path: '/components/selection-panel'
      fullPath: '/components/selection-panel'
      preLoaderRoute: typeof ComponentsSelectionPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/overlay-manager': {
      id: '/components/overlay-manager'
      path: '/components/overlay-manager'
      fullPath: '/components/overlay-manager'
      preLoaderRoute: typeof ComponentsOverlayManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/map': {
      id: '/components/map'
      path: '/components/map'
      fullPath: '/components/map'
      preLoaderRoute: typeof ComponentsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/line-chart': {
      id: '/components/line-chart'
      path: '/components/line-chart'
      fullPath: '/components/line-chart'
      preLoaderRoute: typeof ComponentsLineChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forecast-line-chart': {
      id: '/components/forecast-line-chart'
      path: '/components/forecast-line-chart'
      fullPath: '/components/forecast-line-chart'
      preLoaderRoute: typeof ComponentsForecastLineChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/asset-detail-card': {
      id: '/components/asset-detail-card'
      path: '/components/asset-detail-card'
      fullPath: '/components/asset-detail-card'
      preLoaderRoute: typeof ComponentsAssetDetailCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsAssetDetailCardRoute: ComponentsAssetDetailCardRoute,
  ComponentsForecastLineChartRoute: ComponentsForecastLineChartRoute,
  ComponentsLineChartRoute: ComponentsLineChartRoute,
  ComponentsMapRoute: ComponentsMapRoute,
  ComponentsOverlayManagerRoute: ComponentsOverlayManagerRoute,
  ComponentsSelectionPanelRoute: ComponentsSelectionPanelRoute,
  UtilitiesHelpersRoute: UtilitiesHelpersRoute,
  UtilitiesSchemasRoute: UtilitiesSchemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
